<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-30
 * Time: 下午6:56
 */

namespace app\common\model\lazada;


use think\Model;
use app\common\model\GoodsSku;

class LazadaVariant extends Model
{

    protected $autoWriteTimestamp = true;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function variantAttribute()
    {
        return $this->hasMany(LazadaProductAttribute::class,'vid','id');
    }

    public function variantImages()
    {
        return $this->hasMany(LazadaVariantImage::class,'vid','id');
    }

    public function goodsSku()
    {
        return $this->hasOne(GoodsSku::class,'id','sku_id');
    }
}