<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-28
 * Time: 下午5:59
 */

namespace app\common\model\lazada;

use think\Model;

class LazadaDraft extends Model
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}