<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-30
 * Time: 下午6:56
 */

namespace app\common\model\lazada;

use erp\ErpModel;

class LazadaBrand extends ErpModel
{

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}