<?php
/**
 * Created by PhpStorm.
 * User: joy
 * Date: 18-5-22
 * Time: 下午3:02
 */

namespace app\common\model\lazada;


use think\Model;

class LazadaSite extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}